# Generated by Django 5.2 on 2025-05-01 09:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveIntegerField(help_text='Proficiency percentage (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('devops', 'DevOps'), ('other', 'Other')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_in_chart', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-proficiency'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('technologies', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('ai', 'AI/ML'), ('cloud', 'Cloud Solutions')], max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['-date_created'], name='authapp_pro_date_cr_e7cffb_idx'), models.Index(fields=['category'], name='authapp_pro_categor_95e6cd_idx')],
            },
        ),
    ]
